global:
  scrape_interval: 15s  # default: 15s
scrape_configs:
  - job_name: 'gpu_exporter'
    static_configs:
      - targets: ['nvidia_smi_exporter:9835']  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  
